#################################################################
#                                                               #
#           Home Assistant Main Configuration File              #
#                                                               #
#################################################################
# Loads default set of integrations. Do not remove.
default_config:
config:
#################################################################
# https://www.home-assistant.io/docs/configuration/basic/
homeassistant:
  # Name of the location where Home Assistant is running
  name: Townhead of Aber
  temperature_unit: C
  ### The following installs all package files
  packages: !include_dir_named integrations
  # Location required to calculate the time the sun rises and sets
  latitude: !secret home_lat
  longitude: !secret home_lon
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 40
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: Europe/London
  
  ### The following installs all customizions
  customize: !include customize.yaml
  customize_glob: !include customize_glob.yaml
  auth_providers:
    - type: homeassistant
    - type: trusted_networks
      trusted_networks:
        - 192.168.170.0/24
  #    trusted_users:
  #      192.168.1.24: 4cd6c52e90d84b0a96bda6f9c4b648c4  # User ID

# Load frontend themes from the themes folder
#frontend:
#  themes: !include_dir_merge_named themes

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

#integrations:
#homekit: !include_dir_named integrations/homekit

#homekit:
#- name: Lights
#  port: 50000
#  filter:
#    include_entities:
#      - light.desk_lamp
#      - light.entrance_hall_bulb
#      - light.keiths_lamp
#      - light.overhead_light
#      - light.stairwell_light